name: CI

on: [push]

jobs:
  build:
  
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.10"]   

    name: build-linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout test data
      uses: actions/checkout@v3
      with:
        repository: LebeerLab/SCARAP-testdata
        path: tests/data
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
       conda install pytest
       # for running shell scripts in python
       pip install pytest-shell
       # move data around
       mv tests/data/ delete-me
       mv delete-me/data tests
       rm -r delete-me
       python -m pytest
    
    #- name: Lint with flake8
    #  run: |
    #    conda install flake8
        # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
